### PR TITLE
Move the last two paragraphs out of the Dart subsection

### LINKED ISSUE #3: Move conclusion out of Dart section of planning.MD
The two last paragraphs of the document should not be under the Dart section, but rather in a section named something like "Conclusion".

### PR DESCRIPTION
**Pull request by FredrikAugust**
Closes #3

### CODE REVIEW

**Comment by Kpaubert** [comment]
This could really need a closer review. I've used markdown for over three decades, but can not comprehend this syntax.

**Comment by FredrikAugust** [comment]
I've only used it since the change of millennium so I don't think I'm qualified to review this either.

**Review by AndreasWintherMoen — APPROVED** [review]

**Comment by FredrikAugust** [comment]
I'm sorry, @AndreasWintherMoen, but you have to merge it

**Comment by Kpaubert** [comment]
Toot toot @AndreasWintherMoen

**Pull request merged**
